spring:
  datasource:
#   url: jdbc:h2:tcp://localhost/~/crud
#  driver-class-name: org.h2.Driver
    username: admin
    password: gongsacokaurora
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aurora.gongsacok.com:3306/gongsacokaurora?serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace